[manifest]
version = "0.0.1"
priority = 0

[[patches]]
[patches.pattern]
target = "conf.lua"
pattern = '''_RELEASE_MODE = true'''
position = "after"
payload = '''_RELEASE_MODE = false'''
match_indent = true
