[manifest]
version = "0.0.1"
priority = 0

[[patches]]
[patches.regex]
target = "game.lua"
pattern = "^\\s*(j_.*)$"
position = "at"
payload = "-- removed"
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''if replace_card and (G.P_CENTERS.j_blueprint.unlocked) then'''
position = "at"
payload = '''if replace_card then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:set_ability(center, initial, delay_sprites)'''
position = "after"
payload = "if not center then return end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:init(X, Y, W, H, card, center, params)'''
position = "after"
payload = "if not center then return end"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''function get_joker_win_sticker(_center, index)'''
position = "after"
payload = "if not _center then return end"
match_indent = true

[[patches]]
[patches.copy]
target = "game.lua"
position = "append"
sources = [
    "datapack_loader.lua"
]