[manifest]
version = "0.0.1"
priority = 2

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.P_LOCKED = {}'''
position = "after"
payload = '''
loadDatapacks(self)
self.localization = add_custom_localization(self.localization)
init_localization()
'''
match_indent = true