[manifest]
version = "0.0.1"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local main_menu = nil'''
position = "after"
payload = '''local datapacks = nil'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''main_menu = UIBox_button{ label = {localize('b_main_menu')}, button = "go_to_menu", minw = 5}'''
position = "after"
payload = '''datapacks = UIBox_button{ id = "datapacks_button", label = {localize('b_datapacks')}, button = "datapacks_button", minw = 5}'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''main_menu,'''
position = "after"
payload = '''datapacks,'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", padding = 0, minh = 0.7}, nodes={
            {n=G.UIT.R, config={align = "cm", minw = 3, maxw = 4, minh = 0.6, padding = 0.2, r = 0.1, hover = true, colour = G.C.RED,func = 'can_delete_profile', button = "delete_profile", shadow = true, focus_args = {nav = 'wide'}}, nodes={
              {n=G.UIT.T, config={text = _profile == G.SETTINGS.profile and localize('b_reset_profile') or localize('b_delete_profile'), scale = 0.3, colour = G.C.UI.TEXT_LIGHT}}
            }}
          }},'''
position = "after"
payload = '''{n=G.UIT.R, config={align = "cm", padding = 0, minh = 0.7}, nodes={
    {n=G.UIT.R, config={align = "cm", minw = 3, maxw = 4, minh = 0.6, padding = 0.2, r = 0.1, hover = true, colour = G.C.BLUE, button = "datapacks_button", shadow = true, focus_args = {nav = 'wide'}}, nodes={
      {n=G.UIT.T, config={text = localize("b_datapacks"), scale = 0.3, colour = G.C.UI.TEXT_LIGHT}}
    }}
  }},'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local tarot_options = {}
for i = 1, math.floor(#G.P_CENTER_POOLS.Tarot/11) do
table.insert(tarot_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Tarot/11)))
end'''
position = "at"
payload = '''local tarot_options = {}
for i = 1, math.ceil(#G.P_CENTER_POOLS.Tarot/11) do
table.insert(tarot_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Tarot/11)))
end'''
match_indent = true

[[patches]]
[patches.copy]
target = "functions/UI_definitions.lua"
position = "append"
sources = [
    "UI_definitions.lua"
]

[[patches]]
[patches.copy]
target = "functions/button_callbacks.lua"
position = "append"
sources = [
    "button_callbacks.lua"
]

[[patches]]
[patches.copy]
target = "localization/en-us.lua"
position = "append"
sources = ["add_custom_localization.lua"]