[manifest]
version = "0.0.1"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''challenge_progress = {
            completed = {},
            unlocked = {}
        }'''
position = "after"
payload = ''',
datapacks = {}'''
match_indent = true